joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50  

joint_left_wheel_controller:
  type: velocity_controllers/JointVelocityController
  joint: joint_left_wheel
  

joint_right_wheel_controller:
  type: velocity_controllers/JointVelocityController
  joint: joint_right_wheel
  
     


  
